# Generated by Django 3.2.5 on 2021-07-21 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0004_auto_20210721_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idealist',
            name='created_at',
        ),
        migrations.AddField(
            model_name='idealist',
            name='devtool',
            field=models.CharField(blank=True, choices=[('Node.js', 'Node.js'), ('Spring', 'Spring'), ('Django', 'Django'), ('JavaScript', 'JavaScript')], help_text='예상 개발툴', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='idealist',
            name='image',
            field=models.ImageField(blank=True, help_text='대표 사진', null=True, upload_to='idea_image/%Y/%m/%d/'),
        ),
    ]
