# Generated by Django 3.2.5 on 2021-07-21 04:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0008_alter_idealist_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idealist',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 21, 13, 17, 52, 896344)),
        ),
    ]
