# Generated by Django 3.2.5 on 2021-07-21 06:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0009_alter_idealist_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idealist',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 21, 15, 48, 59, 874614)),
        ),
        migrations.AlterField(
            model_name='idealist',
            name='devtool',
            field=models.CharField(blank=True, choices=[('Node.js', 'Node.js'), ('Spring', 'Spring'), ('django', 'django'), ('JavaScript', 'JavaScript')], help_text='예상 개발툴', max_length=50, null=True),
        ),
    ]
