# Generated by Django 3.2.5 on 2021-07-21 07:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0010_auto_20210721_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idealist',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 21, 16, 27, 14, 925912)),
        ),
        migrations.AlterField(
            model_name='idealist',
            name='devtool',
            field=models.CharField(blank=True, choices=[('Spring', 'Spring'), ('JavaScript', 'JavaScript'), ('django', 'django'), ('Node.js', 'Node.js')], help_text='예상 개발툴', max_length=50, null=True),
        ),
    ]
