# Generated by Django 3.2.5 on 2021-07-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='댓글 내용'),
        ),
    ]
