# Generated by Django 3.2.5 on 2021-07-21 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devtool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='>>이름', max_length=50)),
                ('kind', models.CharField(help_text='>>종류', max_length=50)),
                ('description', models.TextField(blank=True, help_text='>>개발툴 설명')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
